org: gfc0r
service: api-alumno      # ⇦ pon el nombre que quieras

provider:
  name: aws
  runtime: python3.13
  memorySize: 1024
  timeout: 30
  region: us-east-1

  # Usa el mismo rol gestionado que ya tienes en tu cuenta/lab
  iam:
    role: arn:aws:iam::570699102669:role/LabRole

  # Variable para reutilizar el nombre de la tabla por stage
  environment:
    TABLE_NAME: ${sls:stage}-t_alumnos_canvas

functions:
  procesar:
    handler: ProcesarAlumno.lambda_handler        # ⇦ nombre_del_archivo.lambda_handler
    events:
      # Dispara cuando SNS publique en el tópico “NuevoAlumno”
      - sns:
          arn: arn:aws:sns:${aws:region}:570699102669:NuevoAlumno
          topicName: NuevoAlumno

resources:
  Resources:
    TablaAlumnosCanvas:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: alumno_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: alumno_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
